# Generated by Django 4.0.2 on 2022-03-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attachment',
            field=models.FileField(default='a.txt', upload_to='question-attachment/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='user_file_name',
            field=models.CharField(default='a.txt', max_length=200),
            preserve_default=False,
        ),
    ]
