# Generated by Django 4.0.2 on 2022-03-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_alter_question_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='question_attachments/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_file_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
