# Generated by Django 4.0.2 on 2022-03-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_question_attachment_question_user_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='attachment',
            field=models.FileField(upload_to='question_attachments/'),
        ),
    ]
